import { ComplianceDocument } from '@/types/documents'

export const mockDocuments: ComplianceDocument[] = [
  {
    id: 'f4b7b9e2-8c13-4b1d-900a-2a6a9d0d9f7b',
    type: 'Accredited Investor',
    clientName: 'Jordan A. Mercer',
    clientId: 'c-789abc-def',
    status: 'valid',
    issueDate: '2024-10-20',
    expiryDate: '2025-10-20',
    complianceScore: 95,
    riskLevel: 'low',
    tenantId: 'tenant-lighthouse-001',
    version: 1,
    completedBy: 'Alex R. Doyle',
    advisorFirm: 'Lighthouse Capital Advisors',
    regulatoryFramework: ['SEC Reg D Rule 501'],
  },
  {
    id: 'isq-456def-789',
    type: 'Investment Suitability',
    clientName: 'Jordan A. Mercer',
    clientId: 'c-789abc-def',
    status: 'valid',
    issueDate: '2024-10-21',
    expiryDate: '2025-10-21',
    complianceScore: 92,
    riskLevel: 'medium',
    tenantId: 'tenant-lighthouse-001',
    version: 1,
    completedBy: 'Alex R. Doyle',
    advisorFirm: 'Lighthouse Capital Advisors',
    regulatoryFramework: ['SEC', 'FINRA', 'MiFID II'],
  },
  {
    id: 'aird-def789-ghi',
    type: 'Risk Disclosure',
    clientName: 'Jordan A. Mercer',
    clientId: 'c-789abc-def',
    status: 'valid',
    issueDate: '2024-10-21',
    expiryDate: '2025-10-21',
    complianceScore: 88,
    riskLevel: 'high',
    tenantId: 'tenant-lighthouse-001',
    version: 1,
    completedBy: 'Alex R. Doyle',
    advisorFirm: 'Lighthouse Capital Advisors',
    regulatoryFramework: ['SEC Reg D', 'FINRA Rule 2111'],
  },
  {
    id: 'qc-123abc-456',
    type: 'Qualified Client',
    clientName: 'Jordan A. Mercer',
    clientId: 'c-789abc-def',
    status: 'valid',
    issueDate: '2024-10-21',
    expiryDate: '2025-10-21',
    complianceScore: 98,
    riskLevel: 'low',
    tenantId: 'tenant-lighthouse-001',
    version: 1,
    completedBy: 'Alex R. Doyle',
    advisorFirm: 'Lighthouse Capital Advisors',
    regulatoryFramework: ['SEC Rule 205-3'],
  },
  {
    id: 'ai-789xyz-123',
    type: 'Accredited Investor',
    clientName: 'Sarah Johnson',
    clientId: 'c-456def-ghi',
    status: 'expiring',
    issueDate: '2023-11-15',
    expiryDate: '2024-11-15',
    complianceScore: 87,
    riskLevel: 'medium',
    tenantId: 'tenant-lighthouse-001',
    version: 2,
    completedBy: 'Michael Chen',
    advisorFirm: 'Lighthouse Capital Advisors',
    regulatoryFramework: ['SEC Reg D Rule 501'],
  },
  {
    id: 'isq-abc123-xyz',
    type: 'Investment Suitability',
    clientName: 'Robert Williams',
    clientId: 'c-123xyz-abc',
    status: 'expired',
    issueDate: '2023-09-10',
    expiryDate: '2024-09-10',
    complianceScore: 75,
    riskLevel: 'high',
    tenantId: 'tenant-lighthouse-001',
    version: 1,
    completedBy: 'Emily Parker',
    advisorFirm: 'Lighthouse Capital Advisors',
    regulatoryFramework: ['SEC', 'FINRA'],
  },
  {
    id: 'rd-xyz789-def',
    type: 'Risk Disclosure',
    clientName: 'Maria Rodriguez',
    clientId: 'c-789ghi-jkl',
    status: 'pending',
    issueDate: '2024-10-25',
    expiryDate: null,
    complianceScore: null,
    riskLevel: 'medium',
    tenantId: 'tenant-lighthouse-001',
    version: 1,
    completedBy: 'David Lee',
    advisorFirm: 'Lighthouse Capital Advisors',
    regulatoryFramework: ['SEC Reg D'],
  },
  {
    id: 'qc-def456-ghi',
    type: 'Qualified Client',
    clientName: 'James Anderson',
    clientId: 'c-456mno-pqr',
    status: 'valid',
    issueDate: '2024-08-12',
    expiryDate: '2025-08-12',
    complianceScore: 94,
    riskLevel: 'low',
    tenantId: 'tenant-lighthouse-001',
    version: 1,
    completedBy: 'Lisa Thompson',
    advisorFirm: 'Lighthouse Capital Advisors',
    regulatoryFramework: ['SEC Rule 205-3'],
  },
  {
    id: 'ai-mno789-stu',
    type: 'Accredited Investor',
    clientName: 'Jennifer Davis',
    clientId: 'c-789stu-vwx',
    status: 'expiring',
    issueDate: '2023-12-01',
    expiryDate: '2024-12-01',
    complianceScore: 91,
    riskLevel: 'low',
    tenantId: 'tenant-lighthouse-001',
    version: 3,
    completedBy: 'Tom Richards',
    advisorFirm: 'Lighthouse Capital Advisors',
    regulatoryFramework: ['SEC Reg D Rule 501'],
  },
  {
    id: 'isq-stu456-vwx',
    type: 'Investment Suitability',
    clientName: 'Michael Brown',
    clientId: 'c-123vwx-yza',
    status: 'valid',
    issueDate: '2024-07-18',
    expiryDate: '2025-07-18',
    complianceScore: 89,
    riskLevel: 'medium',
    tenantId: 'tenant-lighthouse-001',
    version: 2,
    completedBy: 'Sarah Miller',
    advisorFirm: 'Lighthouse Capital Advisors',
    regulatoryFramework: ['SEC', 'FINRA', 'MiFID II'],
  },
]
